### ISSUE TITLE
Broken Python

### ISSUE THREAD

**Issue by Polarbub** [Lukaja21/Gimkit-Bot#3]
When I run the bot or newbot python scripts it gives a error saying that 
`Traceback (most recent call last):
  File "newbot.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'`
Is there a way I should be doing this or is it broken? I am using python 64 bit v 3.8.5.

**Comment by Canozguur** [comment]
Maybe u should try to add on your command console to install selenium . As command console write (pip install selenium). if it still doesnt work , u should watch " https://youtu.be/k0GyxULn1Iw " this video and do exactly what he does

**Comment by Polarbub** [comment]
So now I get 2 different errors, 
`Traceback (most recent call last):
  File "C:\Users\Bryn\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\temp\random\Gimkit-Bot-master\bot.py", line 12, in <module>
    browser = webdriver.Chrome(executable_path=r'C:\Users\lucas\Documents\chromedriver_win32\chromedriver.exe')
  File "C:\Users\Bryn\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Bryn\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

For the chromedriver error I have the driver in the path variable.

`ECHO %PATH%

C:\Program Files\Python38

dir C:\Program Files\Python38

09/24/2020  09:53 AM         9,615,360 chromedriver.exe

               9 File(s)     15,178,673 bytes
              10 Dir(s)  46,708,764,672 bytes free`

For the subprocess.py error I have no idea. Also is there another version of python I should be using? I am on 3.8.5.

**Comment by Polarbub** [comment]
I fixed this.
